# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from swagger_server.models.address import Address
from swagger_server.models.ai_classification import AiClassification
from swagger_server.models.beneficiary import Beneficiary
from swagger_server.models.benefit import Benefit
from swagger_server.models.body_type import BodyType
from swagger_server.models.claim import Claim
from swagger_server.models.claim_status import ClaimStatus
from swagger_server.models.claim_type import ClaimType
from swagger_server.models.claims_bordereau import ClaimsBordereau
from swagger_server.models.claims_occurrence import ClaimsOccurrence
from swagger_server.models.commercial import Commercial
from swagger_server.models.contract_type import ContractType
from swagger_server.models.conviction import Conviction
from swagger_server.models.currency import Currency
from swagger_server.models.cyber_coverage_categories import CyberCoverageCategories
from swagger_server.models.distance_unit import DistanceUnit
from swagger_server.models.driver import Driver
from swagger_server.models.driving_licence import DrivingLicence
from swagger_server.models.endorsement_type import EndorsementType
from swagger_server.models.entity_classification import EntityClassification
from swagger_server.models.entity_type import EntityType
from swagger_server.models.fuel_type import FuelType
from swagger_server.models.gender import Gender
from swagger_server.models.id_type import IdType
from swagger_server.models.insurance_entity import InsuranceEntity
from swagger_server.models.legal_entity import LegalEntity
from swagger_server.models.medical_condition import MedicalCondition
from swagger_server.models.motor_coverage import MotorCoverage
from swagger_server.models.motor_peril import MotorPeril
from swagger_server.models.notifiable_condition import NotifiableCondition
from swagger_server.models.offence_code import OffenceCode
from swagger_server.models.payment_method import PaymentMethod
from swagger_server.models.personal import Personal
from swagger_server.models.pet import Pet
from swagger_server.models.pet_benefits import PetBenefits
from swagger_server.models.pet_breed import PetBreed
from swagger_server.models.pet_kind import PetKind
from swagger_server.models.policy_status import PolicyStatus
from swagger_server.models.policy_wording import PolicyWording
from swagger_server.models.premium_bordereau import PremiumBordereau
from swagger_server.models.premium_payment_frequency import PremiumPaymentFrequency
from swagger_server.models.product import Product
from swagger_server.models.product_catalog import ProductCatalog
from swagger_server.models.product_model import ProductModel
from swagger_server.models.property_peril import PropertyPeril
from swagger_server.models.property_type import PropertyType
from swagger_server.models.receipt import Receipt
from swagger_server.models.receipt_calculation import ReceiptCalculation
from swagger_server.models.receipt_type import ReceiptType
from swagger_server.models.root_construction import RootConstruction
from swagger_server.models.salutation import Salutation
from swagger_server.models.term_life_riders import TermLifeRiders
from swagger_server.models.term_life_type import TermLifeType
from swagger_server.models.trade_credit_peril import TradeCreditPeril
from swagger_server.models.type_business_interruption import TypeBusinessInterruption
from swagger_server.models.vehicle import Vehicle
from swagger_server.models.vehicle_use import VehicleUse
from swagger_server.models.wall_construction import WallConstruction
from swagger_server.models.workstatus import Workstatus
