# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Benefit(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PERSONAL_ACCIDENT = "personal accident"
    REPLACEMENT_VEHICLE = "replacement vehicle"
    ROADSIDE_ASSISSTANCE = "roadside assisstance"
    def __init__(self):  # noqa: E501
        """Benefit - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Benefit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The benefit of this Benefit.  # noqa: E501
        :rtype: Benefit
        """
        return util.deserialize_model(dikt, cls)
