# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BodyType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    MOTOR_CAR = "motor car"
    MOTORCYCLE = "motorcycle"
    MOTORIZED_TRICYCLE = "motorized tricycle"
    ELECTRIC_SCOOTER = "electric scooter"
    QUADCYCLE = "quadcycle"
    TRAILER_HEAD = "trailer head"
    VAN = "van"
    BUS = "bus"
    TRACKTOR = "tracktor"
    POD = "pod"
    MOTOR_HOME = "motor home"
    CONSTRUCTION_EQUIPMENT = "construction equipment"
    def __init__(self):  # noqa: E501
        """BodyType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'BodyType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bodyType of this BodyType.  # noqa: E501
        :rtype: BodyType
        """
        return util.deserialize_model(dikt, cls)
