# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ClaimsBordereau(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, treaty_reference: str=None, policyholder: str=None, policy_number: str=None, inception_date: date=None, expiry_date: date=None, indemnity_limit_policy: float=None, claim_number: str=None, fnol: date=None, date_of_loss: date=None, cause_of_loss: str=None, claimant: str=None, grossl_loss_reserve: float=None, excess_amount: float=None, expense_reserve: float=None, paid: float=None, expenses_paid: float=None, expected_recovery: float=None, recovery_received: float=None, claim_status: str=None):  # noqa: E501
        """ClaimsBordereau - a model defined in Swagger

        :param treaty_reference: The treaty_reference of this ClaimsBordereau.  # noqa: E501
        :type treaty_reference: str
        :param policyholder: The policyholder of this ClaimsBordereau.  # noqa: E501
        :type policyholder: str
        :param policy_number: The policy_number of this ClaimsBordereau.  # noqa: E501
        :type policy_number: str
        :param inception_date: The inception_date of this ClaimsBordereau.  # noqa: E501
        :type inception_date: date
        :param expiry_date: The expiry_date of this ClaimsBordereau.  # noqa: E501
        :type expiry_date: date
        :param indemnity_limit_policy: The indemnity_limit_policy of this ClaimsBordereau.  # noqa: E501
        :type indemnity_limit_policy: float
        :param claim_number: The claim_number of this ClaimsBordereau.  # noqa: E501
        :type claim_number: str
        :param fnol: The fnol of this ClaimsBordereau.  # noqa: E501
        :type fnol: date
        :param date_of_loss: The date_of_loss of this ClaimsBordereau.  # noqa: E501
        :type date_of_loss: date
        :param cause_of_loss: The cause_of_loss of this ClaimsBordereau.  # noqa: E501
        :type cause_of_loss: str
        :param claimant: The claimant of this ClaimsBordereau.  # noqa: E501
        :type claimant: str
        :param grossl_loss_reserve: The grossl_loss_reserve of this ClaimsBordereau.  # noqa: E501
        :type grossl_loss_reserve: float
        :param excess_amount: The excess_amount of this ClaimsBordereau.  # noqa: E501
        :type excess_amount: float
        :param expense_reserve: The expense_reserve of this ClaimsBordereau.  # noqa: E501
        :type expense_reserve: float
        :param paid: The paid of this ClaimsBordereau.  # noqa: E501
        :type paid: float
        :param expenses_paid: The expenses_paid of this ClaimsBordereau.  # noqa: E501
        :type expenses_paid: float
        :param expected_recovery: The expected_recovery of this ClaimsBordereau.  # noqa: E501
        :type expected_recovery: float
        :param recovery_received: The recovery_received of this ClaimsBordereau.  # noqa: E501
        :type recovery_received: float
        :param claim_status: The claim_status of this ClaimsBordereau.  # noqa: E501
        :type claim_status: str
        """
        self.swagger_types = {
            'treaty_reference': str,
            'policyholder': str,
            'policy_number': str,
            'inception_date': date,
            'expiry_date': date,
            'indemnity_limit_policy': float,
            'claim_number': str,
            'fnol': date,
            'date_of_loss': date,
            'cause_of_loss': str,
            'claimant': str,
            'grossl_loss_reserve': float,
            'excess_amount': float,
            'expense_reserve': float,
            'paid': float,
            'expenses_paid': float,
            'expected_recovery': float,
            'recovery_received': float,
            'claim_status': str
        }

        self.attribute_map = {
            'treaty_reference': 'treatyReference',
            'policyholder': 'policyholder',
            'policy_number': 'policyNumber',
            'inception_date': 'inceptionDate',
            'expiry_date': 'expiryDate',
            'indemnity_limit_policy': 'indemnityLimitPolicy',
            'claim_number': 'claimNumber',
            'fnol': 'fnol',
            'date_of_loss': 'dateOfLoss',
            'cause_of_loss': 'causeOfLoss',
            'claimant': 'claimant',
            'grossl_loss_reserve': 'GrosslLossReserve',
            'excess_amount': 'excessAmount',
            'expense_reserve': 'expenseReserve',
            'paid': 'paid',
            'expenses_paid': 'expensesPaid',
            'expected_recovery': 'expectedRecovery',
            'recovery_received': 'recoveryReceived',
            'claim_status': 'claimStatus'
        }
        self._treaty_reference = treaty_reference
        self._policyholder = policyholder
        self._policy_number = policy_number
        self._inception_date = inception_date
        self._expiry_date = expiry_date
        self._indemnity_limit_policy = indemnity_limit_policy
        self._claim_number = claim_number
        self._fnol = fnol
        self._date_of_loss = date_of_loss
        self._cause_of_loss = cause_of_loss
        self._claimant = claimant
        self._grossl_loss_reserve = grossl_loss_reserve
        self._excess_amount = excess_amount
        self._expense_reserve = expense_reserve
        self._paid = paid
        self._expenses_paid = expenses_paid
        self._expected_recovery = expected_recovery
        self._recovery_received = recovery_received
        self._claim_status = claim_status

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimsBordereau':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimsBordereau of this ClaimsBordereau.  # noqa: E501
        :rtype: ClaimsBordereau
        """
        return util.deserialize_model(dikt, cls)

    @property
    def treaty_reference(self) -> str:
        """Gets the treaty_reference of this ClaimsBordereau.


        :return: The treaty_reference of this ClaimsBordereau.
        :rtype: str
        """
        return self._treaty_reference

    @treaty_reference.setter
    def treaty_reference(self, treaty_reference: str):
        """Sets the treaty_reference of this ClaimsBordereau.


        :param treaty_reference: The treaty_reference of this ClaimsBordereau.
        :type treaty_reference: str
        """

        self._treaty_reference = treaty_reference

    @property
    def policyholder(self) -> str:
        """Gets the policyholder of this ClaimsBordereau.


        :return: The policyholder of this ClaimsBordereau.
        :rtype: str
        """
        return self._policyholder

    @policyholder.setter
    def policyholder(self, policyholder: str):
        """Sets the policyholder of this ClaimsBordereau.


        :param policyholder: The policyholder of this ClaimsBordereau.
        :type policyholder: str
        """

        self._policyholder = policyholder

    @property
    def policy_number(self) -> str:
        """Gets the policy_number of this ClaimsBordereau.


        :return: The policy_number of this ClaimsBordereau.
        :rtype: str
        """
        return self._policy_number

    @policy_number.setter
    def policy_number(self, policy_number: str):
        """Sets the policy_number of this ClaimsBordereau.


        :param policy_number: The policy_number of this ClaimsBordereau.
        :type policy_number: str
        """

        self._policy_number = policy_number

    @property
    def inception_date(self) -> date:
        """Gets the inception_date of this ClaimsBordereau.


        :return: The inception_date of this ClaimsBordereau.
        :rtype: date
        """
        return self._inception_date

    @inception_date.setter
    def inception_date(self, inception_date: date):
        """Sets the inception_date of this ClaimsBordereau.


        :param inception_date: The inception_date of this ClaimsBordereau.
        :type inception_date: date
        """

        self._inception_date = inception_date

    @property
    def expiry_date(self) -> date:
        """Gets the expiry_date of this ClaimsBordereau.


        :return: The expiry_date of this ClaimsBordereau.
        :rtype: date
        """
        return self._expiry_date

    @expiry_date.setter
    def expiry_date(self, expiry_date: date):
        """Sets the expiry_date of this ClaimsBordereau.


        :param expiry_date: The expiry_date of this ClaimsBordereau.
        :type expiry_date: date
        """

        self._expiry_date = expiry_date

    @property
    def indemnity_limit_policy(self) -> float:
        """Gets the indemnity_limit_policy of this ClaimsBordereau.


        :return: The indemnity_limit_policy of this ClaimsBordereau.
        :rtype: float
        """
        return self._indemnity_limit_policy

    @indemnity_limit_policy.setter
    def indemnity_limit_policy(self, indemnity_limit_policy: float):
        """Sets the indemnity_limit_policy of this ClaimsBordereau.


        :param indemnity_limit_policy: The indemnity_limit_policy of this ClaimsBordereau.
        :type indemnity_limit_policy: float
        """

        self._indemnity_limit_policy = indemnity_limit_policy

    @property
    def claim_number(self) -> str:
        """Gets the claim_number of this ClaimsBordereau.


        :return: The claim_number of this ClaimsBordereau.
        :rtype: str
        """
        return self._claim_number

    @claim_number.setter
    def claim_number(self, claim_number: str):
        """Sets the claim_number of this ClaimsBordereau.


        :param claim_number: The claim_number of this ClaimsBordereau.
        :type claim_number: str
        """

        self._claim_number = claim_number

    @property
    def fnol(self) -> date:
        """Gets the fnol of this ClaimsBordereau.


        :return: The fnol of this ClaimsBordereau.
        :rtype: date
        """
        return self._fnol

    @fnol.setter
    def fnol(self, fnol: date):
        """Sets the fnol of this ClaimsBordereau.


        :param fnol: The fnol of this ClaimsBordereau.
        :type fnol: date
        """

        self._fnol = fnol

    @property
    def date_of_loss(self) -> date:
        """Gets the date_of_loss of this ClaimsBordereau.


        :return: The date_of_loss of this ClaimsBordereau.
        :rtype: date
        """
        return self._date_of_loss

    @date_of_loss.setter
    def date_of_loss(self, date_of_loss: date):
        """Sets the date_of_loss of this ClaimsBordereau.


        :param date_of_loss: The date_of_loss of this ClaimsBordereau.
        :type date_of_loss: date
        """

        self._date_of_loss = date_of_loss

    @property
    def cause_of_loss(self) -> str:
        """Gets the cause_of_loss of this ClaimsBordereau.


        :return: The cause_of_loss of this ClaimsBordereau.
        :rtype: str
        """
        return self._cause_of_loss

    @cause_of_loss.setter
    def cause_of_loss(self, cause_of_loss: str):
        """Sets the cause_of_loss of this ClaimsBordereau.


        :param cause_of_loss: The cause_of_loss of this ClaimsBordereau.
        :type cause_of_loss: str
        """

        self._cause_of_loss = cause_of_loss

    @property
    def claimant(self) -> str:
        """Gets the claimant of this ClaimsBordereau.


        :return: The claimant of this ClaimsBordereau.
        :rtype: str
        """
        return self._claimant

    @claimant.setter
    def claimant(self, claimant: str):
        """Sets the claimant of this ClaimsBordereau.


        :param claimant: The claimant of this ClaimsBordereau.
        :type claimant: str
        """

        self._claimant = claimant

    @property
    def grossl_loss_reserve(self) -> float:
        """Gets the grossl_loss_reserve of this ClaimsBordereau.


        :return: The grossl_loss_reserve of this ClaimsBordereau.
        :rtype: float
        """
        return self._grossl_loss_reserve

    @grossl_loss_reserve.setter
    def grossl_loss_reserve(self, grossl_loss_reserve: float):
        """Sets the grossl_loss_reserve of this ClaimsBordereau.


        :param grossl_loss_reserve: The grossl_loss_reserve of this ClaimsBordereau.
        :type grossl_loss_reserve: float
        """

        self._grossl_loss_reserve = grossl_loss_reserve

    @property
    def excess_amount(self) -> float:
        """Gets the excess_amount of this ClaimsBordereau.


        :return: The excess_amount of this ClaimsBordereau.
        :rtype: float
        """
        return self._excess_amount

    @excess_amount.setter
    def excess_amount(self, excess_amount: float):
        """Sets the excess_amount of this ClaimsBordereau.


        :param excess_amount: The excess_amount of this ClaimsBordereau.
        :type excess_amount: float
        """

        self._excess_amount = excess_amount

    @property
    def expense_reserve(self) -> float:
        """Gets the expense_reserve of this ClaimsBordereau.


        :return: The expense_reserve of this ClaimsBordereau.
        :rtype: float
        """
        return self._expense_reserve

    @expense_reserve.setter
    def expense_reserve(self, expense_reserve: float):
        """Sets the expense_reserve of this ClaimsBordereau.


        :param expense_reserve: The expense_reserve of this ClaimsBordereau.
        :type expense_reserve: float
        """

        self._expense_reserve = expense_reserve

    @property
    def paid(self) -> float:
        """Gets the paid of this ClaimsBordereau.


        :return: The paid of this ClaimsBordereau.
        :rtype: float
        """
        return self._paid

    @paid.setter
    def paid(self, paid: float):
        """Sets the paid of this ClaimsBordereau.


        :param paid: The paid of this ClaimsBordereau.
        :type paid: float
        """

        self._paid = paid

    @property
    def expenses_paid(self) -> float:
        """Gets the expenses_paid of this ClaimsBordereau.


        :return: The expenses_paid of this ClaimsBordereau.
        :rtype: float
        """
        return self._expenses_paid

    @expenses_paid.setter
    def expenses_paid(self, expenses_paid: float):
        """Sets the expenses_paid of this ClaimsBordereau.


        :param expenses_paid: The expenses_paid of this ClaimsBordereau.
        :type expenses_paid: float
        """

        self._expenses_paid = expenses_paid

    @property
    def expected_recovery(self) -> float:
        """Gets the expected_recovery of this ClaimsBordereau.


        :return: The expected_recovery of this ClaimsBordereau.
        :rtype: float
        """
        return self._expected_recovery

    @expected_recovery.setter
    def expected_recovery(self, expected_recovery: float):
        """Sets the expected_recovery of this ClaimsBordereau.


        :param expected_recovery: The expected_recovery of this ClaimsBordereau.
        :type expected_recovery: float
        """

        self._expected_recovery = expected_recovery

    @property
    def recovery_received(self) -> float:
        """Gets the recovery_received of this ClaimsBordereau.


        :return: The recovery_received of this ClaimsBordereau.
        :rtype: float
        """
        return self._recovery_received

    @recovery_received.setter
    def recovery_received(self, recovery_received: float):
        """Sets the recovery_received of this ClaimsBordereau.


        :param recovery_received: The recovery_received of this ClaimsBordereau.
        :type recovery_received: float
        """

        self._recovery_received = recovery_received

    @property
    def claim_status(self) -> str:
        """Gets the claim_status of this ClaimsBordereau.


        :return: The claim_status of this ClaimsBordereau.
        :rtype: str
        """
        return self._claim_status

    @claim_status.setter
    def claim_status(self, claim_status: str):
        """Sets the claim_status of this ClaimsBordereau.


        :param claim_status: The claim_status of this ClaimsBordereau.
        :type claim_status: str
        """

        self._claim_status = claim_status
