# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntityType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    REINSURANCE_COMPANY = "reinsurance company"
    INSURANCE_COMPANY = "insurance company"
    TAKAFUL_REINSURANCE_COMAPNY = "takaful reinsurance comapny"
    TAKAFUL_INSURANCE_COMPANY = "takaful insurance company"
    MUTUAL_INSURANCE_COMPANY = "mutual insurance company"
    PEER_TO_PEER_INSURANCE_COMPANY = "peer-to-peer insurance company"
    LLOYDS_SYNDICATE = "Lloyds syndicate"
    REINSURANCE_POOL = "reinsurance pool"
    CAPTIVE_INSURANCE_COMPANY = "captive insurance company"
    DECENTRALIZED_AUTONOMOUS_ORGANIZATION = "decentralized autonomous organization"
    INSURANCE_BROKER = "insurance broker"
    INSURANCE_AGENT = "insurance agent"
    MANAGING_GENERAL_AGENT = "managing general agent"
    INSURANCE_INTRODUCER = "insurance introducer"
    PRICE_AGGREGATOR = "price aggregator"
    INSURANCE_PREDICTION_MARKET = "insurance prediction market"
    OTHER = "other"
    def __init__(self):  # noqa: E501
        """EntityType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'EntityType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The entityType of this EntityType.  # noqa: E501
        :rtype: EntityType
        """
        return util.deserialize_model(dikt, cls)
