# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FuelType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PETROL = "petrol"
    DIESEL = "diesel"
    ELECTRIC = "electric"
    PETROL_ELECTRIC_HYBRID = "petrol/electric hybrid"
    GAS = "gas"
    HYDROGEN = "hydrogen"
    def __init__(self):  # noqa: E501
        """FuelType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'FuelType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The fuelType of this FuelType.  # noqa: E501
        :rtype: FuelType
        """
        return util.deserialize_model(dikt, cls)
