# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LegalEntity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SOLE_TRADER = "sole trader"
    PRIVATE_LIMITED_COMPANY = "private limited company"
    PUBLIC_LIMITED_COMPANY = "public limited company"
    GENERAL_PARTNERSHIPS = "general partnerships"
    LIMITED_PARTNERSHIP = "limited partnership"
    def __init__(self):  # noqa: E501
        """LegalEntity - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'LegalEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The legalEntity of this LegalEntity.  # noqa: E501
        :rtype: LegalEntity
        """
        return util.deserialize_model(dikt, cls)
