# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MotorPeril(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    LIABILITY_TOWARDS_THIRD_PARTIES = "liability towards third parties"
    FIRE = "fire"
    THEFT = "theft"
    ACCIDENTAL_DAMAGE = "accidental damage"
    WINDSHIELD_DAMAGE = "windshield damage"
    MALICIOUS_DAMAGE = "malicious damage"
    TERRORISM_AND_SABOTAGE = "terrorism and sabotage"
    FLOOD = "flood"
    EARTHQUAKE = "earthquake"
    VOLCANIC_ERRUPTION = "volcanic erruption"
    TSUNAMI = "tsunami"
    HAIL = "hail"
    UNKOWN_OR_HIT_AND_RUN = "unkown or hit and run"
    RIOTS = "riots"
    STRIKES = "strikes"
    CIVIL_COMMOTION = "civil commotion"
    WAR = "war"
    def __init__(self):  # noqa: E501
        """MotorPeril - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'MotorPeril':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The motorPeril of this MotorPeril.  # noqa: E501
        :rtype: MotorPeril
        """
        return util.deserialize_model(dikt, cls)
