# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NotifiableCondition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DIABETES = "diabetes"
    SYNCOPE = "syncope"
    HEART_CONDITION = "heart condition"
    SLEEP_APONEA = "sleep aponea"
    EPILEPSY = "epilepsy"
    STROKES = "strokes"
    NULL = 
    def __init__(self):  # noqa: E501
        """NotifiableCondition - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NotifiableCondition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The notifiableCondition of this NotifiableCondition.  # noqa: E501
        :rtype: NotifiableCondition
        """
        return util.deserialize_model(dikt, cls)
