# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OffenceCode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AC10 = "AC10"
    AC20 = "AC20"
    AC30 = "AC30"
    BA10 = "BA10"
    BA30 = "BA30"
    BA40 = "BA40"
    BA60 = "BA60"
    CD10 = "CD10"
    CD20 = "CD20"
    CD30 = "CD30"
    CD40 = "CD40"
    CD50 = "CD50"
    CD60 = "CD60"
    CD70 = "CD70"
    CD80 = "CD80"
    CD90 = "CD90"
    CU10 = "CU10"
    CU20 = "CU20"
    CU30 = "CU30"
    CU40 = "CU40"
    CU50 = "CU50"
    CU80 = "CU80"
    DD10 = "DD10"
    DD40 = "DD40"
    DD60 = "DD60"
    DD80_DD90_DR10_DR20_DR30_DR31_DR61_DR40_DR50_DR60_DR70_DG10_DG60_DR80_DG40_DR70_DR90_IN10_LC20_LC30_LC40_LC50_MS10_MS20_MS30_MS50_MS60_MS70_MS80_MS90_MW10_PC10_PC20_PC30_SP10_SP20_SP30_SP40_SP50_TS10_TS20_TS30_TS40_TS50_TS60_TS70_UT50_MR09_MR19_MR29_MR39_MR49_MR59 = "DD80 - DD90 - DR10 - DR20 - DR30 - DR31 - DR61 - DR40 - DR50 - DR60 - DR70 - DG10 - DG60 - DR80 - DG40 - DR70 - DR90 - IN10 - LC20 - LC30 - LC40 - LC50 - MS10 - MS20 - MS30 - MS50 - MS60 - MS70 - MS80 - MS90 - MW10 - PC10 - PC20 - PC30 - SP10 - SP20 - SP30 - SP40 - SP50 - TS10 - TS20 - TS30 - TS40 - TS50 - TS60 - TS70 - UT50 - MR09 - MR19 - MR29 - MR39 - MR49 - MR59"
    def __init__(self):  # noqa: E501
        """OffenceCode - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OffenceCode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The offenceCode of this OffenceCode.  # noqa: E501
        :rtype: OffenceCode
        """
        return util.deserialize_model(dikt, cls)
