# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PremiumBordereau(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, treaty_reference: str=None, policyholder: str=None, policy_number: str=None, inception_date: date=None, expiry_date: date=None, indemnity_limit_policy: float=None, gross_written_premium: float=None, net_premium: float=None, transaction_type: str=None):  # noqa: E501
        """PremiumBordereau - a model defined in Swagger

        :param treaty_reference: The treaty_reference of this PremiumBordereau.  # noqa: E501
        :type treaty_reference: str
        :param policyholder: The policyholder of this PremiumBordereau.  # noqa: E501
        :type policyholder: str
        :param policy_number: The policy_number of this PremiumBordereau.  # noqa: E501
        :type policy_number: str
        :param inception_date: The inception_date of this PremiumBordereau.  # noqa: E501
        :type inception_date: date
        :param expiry_date: The expiry_date of this PremiumBordereau.  # noqa: E501
        :type expiry_date: date
        :param indemnity_limit_policy: The indemnity_limit_policy of this PremiumBordereau.  # noqa: E501
        :type indemnity_limit_policy: float
        :param gross_written_premium: The gross_written_premium of this PremiumBordereau.  # noqa: E501
        :type gross_written_premium: float
        :param net_premium: The net_premium of this PremiumBordereau.  # noqa: E501
        :type net_premium: float
        :param transaction_type: The transaction_type of this PremiumBordereau.  # noqa: E501
        :type transaction_type: str
        """
        self.swagger_types = {
            'treaty_reference': str,
            'policyholder': str,
            'policy_number': str,
            'inception_date': date,
            'expiry_date': date,
            'indemnity_limit_policy': float,
            'gross_written_premium': float,
            'net_premium': float,
            'transaction_type': str
        }

        self.attribute_map = {
            'treaty_reference': 'treatyReference',
            'policyholder': 'policyholder',
            'policy_number': 'policyNumber',
            'inception_date': 'inceptionDate',
            'expiry_date': 'expiryDate',
            'indemnity_limit_policy': 'indemnityLimitPolicy',
            'gross_written_premium': 'grossWrittenPremium',
            'net_premium': 'netPremium',
            'transaction_type': 'transactionType'
        }
        self._treaty_reference = treaty_reference
        self._policyholder = policyholder
        self._policy_number = policy_number
        self._inception_date = inception_date
        self._expiry_date = expiry_date
        self._indemnity_limit_policy = indemnity_limit_policy
        self._gross_written_premium = gross_written_premium
        self._net_premium = net_premium
        self._transaction_type = transaction_type

    @classmethod
    def from_dict(cls, dikt) -> 'PremiumBordereau':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PremiumBordereau of this PremiumBordereau.  # noqa: E501
        :rtype: PremiumBordereau
        """
        return util.deserialize_model(dikt, cls)

    @property
    def treaty_reference(self) -> str:
        """Gets the treaty_reference of this PremiumBordereau.


        :return: The treaty_reference of this PremiumBordereau.
        :rtype: str
        """
        return self._treaty_reference

    @treaty_reference.setter
    def treaty_reference(self, treaty_reference: str):
        """Sets the treaty_reference of this PremiumBordereau.


        :param treaty_reference: The treaty_reference of this PremiumBordereau.
        :type treaty_reference: str
        """

        self._treaty_reference = treaty_reference

    @property
    def policyholder(self) -> str:
        """Gets the policyholder of this PremiumBordereau.


        :return: The policyholder of this PremiumBordereau.
        :rtype: str
        """
        return self._policyholder

    @policyholder.setter
    def policyholder(self, policyholder: str):
        """Sets the policyholder of this PremiumBordereau.


        :param policyholder: The policyholder of this PremiumBordereau.
        :type policyholder: str
        """

        self._policyholder = policyholder

    @property
    def policy_number(self) -> str:
        """Gets the policy_number of this PremiumBordereau.


        :return: The policy_number of this PremiumBordereau.
        :rtype: str
        """
        return self._policy_number

    @policy_number.setter
    def policy_number(self, policy_number: str):
        """Sets the policy_number of this PremiumBordereau.


        :param policy_number: The policy_number of this PremiumBordereau.
        :type policy_number: str
        """

        self._policy_number = policy_number

    @property
    def inception_date(self) -> date:
        """Gets the inception_date of this PremiumBordereau.


        :return: The inception_date of this PremiumBordereau.
        :rtype: date
        """
        return self._inception_date

    @inception_date.setter
    def inception_date(self, inception_date: date):
        """Sets the inception_date of this PremiumBordereau.


        :param inception_date: The inception_date of this PremiumBordereau.
        :type inception_date: date
        """

        self._inception_date = inception_date

    @property
    def expiry_date(self) -> date:
        """Gets the expiry_date of this PremiumBordereau.


        :return: The expiry_date of this PremiumBordereau.
        :rtype: date
        """
        return self._expiry_date

    @expiry_date.setter
    def expiry_date(self, expiry_date: date):
        """Sets the expiry_date of this PremiumBordereau.


        :param expiry_date: The expiry_date of this PremiumBordereau.
        :type expiry_date: date
        """

        self._expiry_date = expiry_date

    @property
    def indemnity_limit_policy(self) -> float:
        """Gets the indemnity_limit_policy of this PremiumBordereau.


        :return: The indemnity_limit_policy of this PremiumBordereau.
        :rtype: float
        """
        return self._indemnity_limit_policy

    @indemnity_limit_policy.setter
    def indemnity_limit_policy(self, indemnity_limit_policy: float):
        """Sets the indemnity_limit_policy of this PremiumBordereau.


        :param indemnity_limit_policy: The indemnity_limit_policy of this PremiumBordereau.
        :type indemnity_limit_policy: float
        """

        self._indemnity_limit_policy = indemnity_limit_policy

    @property
    def gross_written_premium(self) -> float:
        """Gets the gross_written_premium of this PremiumBordereau.


        :return: The gross_written_premium of this PremiumBordereau.
        :rtype: float
        """
        return self._gross_written_premium

    @gross_written_premium.setter
    def gross_written_premium(self, gross_written_premium: float):
        """Sets the gross_written_premium of this PremiumBordereau.


        :param gross_written_premium: The gross_written_premium of this PremiumBordereau.
        :type gross_written_premium: float
        """

        self._gross_written_premium = gross_written_premium

    @property
    def net_premium(self) -> float:
        """Gets the net_premium of this PremiumBordereau.


        :return: The net_premium of this PremiumBordereau.
        :rtype: float
        """
        return self._net_premium

    @net_premium.setter
    def net_premium(self, net_premium: float):
        """Sets the net_premium of this PremiumBordereau.


        :param net_premium: The net_premium of this PremiumBordereau.
        :type net_premium: float
        """

        self._net_premium = net_premium

    @property
    def transaction_type(self) -> str:
        """Gets the transaction_type of this PremiumBordereau.


        :return: The transaction_type of this PremiumBordereau.
        :rtype: str
        """
        return self._transaction_type

    @transaction_type.setter
    def transaction_type(self, transaction_type: str):
        """Sets the transaction_type of this PremiumBordereau.


        :param transaction_type: The transaction_type of this PremiumBordereau.
        :type transaction_type: str
        """

        self._transaction_type = transaction_type
