# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProductCatalog(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PROPERTY_FIRE_INSURANCE = "property fire insurance"
    BURGLARY_INSURANCE = "burglary insurance"
    RENTERS_INSURANCE = "renters insurance"
    HOME_AND_CONTENT_INSURANCE = "home and content insurance"
    PROPERTY_FLOOD_INSURANCE = "property flood insurance"
    DEBRIS_REMOVAL_INSURANCE = "debris removal insurance"
    MOTOR_COMPREHENSIVE_INSURANCE = "motor comprehensive insurance"
    MOTOR_THIRD_PARTY_LIABILITY_INSURANCE = "motor third party liability insurance"
    LAND_TRANSIT_INSURANCE = "land transit insurance"
    MARINE_CARGO_INSURANCE = "marine cargo insurance"
    MARINE_HULL_AND_MACHINERY_INSURANCE = "marine hull and machinery insurance"
    MARINE_PROTECTION_AND_INDEMNITY = "marine protection and indemnity"
    CARRIERS_LIABILITY_INSURANCE = "carriers liability insurance"
    MEDICAL_INSURANCE = "medical insurance"
    CONSTRUCTION_ALL_RISKS_INSURANCE = "construction all risks insurance"
    ENGINEERING_CONTRACTOR_PLANT_AND_MACHINERY_INSURANCE = "engineering contractor plant and machinery insurance"
    ELECTRONIC_EQUIPMENT_INSURANCE = "electronic equipment insurance"
    EQUIPMENT_BREAKDOWN_INSURANCE = "equipment breakdown insurance"
    DECENIAL_LIABILITY_INSURANCE = "decenial liability insurance"
    DETERIORATION_OF_STOCK_INSURANCE = "deterioration of stock insurance"
    BOILER_AND_MACHINERY_INSURANCE = "boiler and machinery insurance"
    GLASS_INSURANCE = "glass insurance"
    MONEY_CASH_IN_TRANSIT_INSURANCE = "money cash in transit insurance"
    MONEY_CASH_IN_SAFE_INSURANCE = "money cash in safe insurance"
    FIDELITY_GUARANTEE_INSURANCE = "fidelity guarantee insurance"
    WORKERS_COMPENSATION_INSURANCE = "workers compensation insurance"
    PET_INSURANCE = "pet insurance"
    BLOODSTOCK_INSURANCE = "bloodstock insurance"
    LIVESTOCK_INSURANCE = "livestock insurance"
    PERSONAL_ACCIDENT_INSURANCE = "personal accident insurance"
    TERM_LIFE_INSURANCE = "term life insurance"
    WHOLE_OF_LIFE_INSURANCE = "whole of life insurance"
    MEDICAL_MALPRACTICE_INSURANCE = "medical malpractice insurance"
    PROFESSIONAL_INDEMNITY_INSURANCE = "professional indemnity insurance"
    TRADE_CREDIT_INSURANCE = "trade credit insurance"
    PURCHASE_PROTECTION_INSURANCE = "purchase protection insurance"
    TRAVEL_INSURANCE = "travel insurance"
    LEGAL_EXPENSE_INSURANCE = "legal expense insurance"
    CYBER_LIABILITY_INSURANCE = "cyber liability insurance"
    BUSINESS_INTERRUPTION_INSURANCE = "business interruption insurance"
    DIRECTORS_AND_OFFICERS_INSURANCE = "directors and officers insurance"
    KEY_PERSON_INSURANCE = "key person insurance"
    COMMERCIAL_GENERAL_LIABILITY = "commercial general liability"
    EMPLOYERS_LIABILITY_INSURANCE = "employers liability insurance"
    ENVIRONMENTAL_LIABILITY_INSURANCE = "environmental liability insurance"
    PRODUCTS_LIABILITY_INSURANCE = "products liability insurance"
    PROPERTY_TERRORISM_AND_SABOTAGE_INSURANCE = "property terrorism and sabotage insurance"
    BUSINESS_OWNERS_INSURANCE = "business owners insurance"
    ERRORS_AND_OMMISSIONS_INSURANCE = "errors and ommissions insurance"
    COMMERCIAL_UMBRELLA_INSURANCE = "commercial umbrella insurance"
    EVENT_INSURANCE = "event insurance"
    PASSENGER_LIABILITY_INSURANCE_AVIATION_ = "passenger liability insurance (aviation)"
    GROUND_RISK_HULL_INSURANCE_AVIATION_ = "ground risk hull insurance (aviation)"
    IN_FLIGHT_INSURANCE_AVIATION_ = "in-flight insurance (aviation)"
    ROADSIDE_ASSISTANCE = "roadside assistance"
    CROP_INSURANCE = "crop insurance"
    DRONE_INSURANCE = "drone insurance"
    GAP_INSURANCE = "gap insurance"
    GREEN_CARD = "green card"
    ORANGE_CARD = "orange card"
    INVESTMENT_SAVING_ACCOUNT_UK_MARKET_RELATED_ = "Investment Saving Account (UK market related)"
    PENSION = "pension"
    ENDOWMENT = "endowment"
    ANNUITY = "annuity"
    WEDDING_RING_INSURANCE = "wedding ring insurance"
    def __init__(self):  # noqa: E501
        """ProductCatalog - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ProductCatalog':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The productCatalog of this ProductCatalog.  # noqa: E501
        :rtype: ProductCatalog
        """
        return util.deserialize_model(dikt, cls)
