# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PropertyPeril(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AIRCRAFT_OR_PARTS_DROPEED_THEREOF = "aircraft or parts dropeed thereof"
    AVALANCHE = "Avalanche"
    BURGLARY = "Burglary"
    BURST_PIPES_OR_WATER_APPARATUS = "Burst pipes or water apparatus"
    CIVIL_COMMOTIONS = "Civil Commotions"
    COASTAL_FLOOD = "Coastal flood"
    CYCLONE = "Cyclone"
    EARTHQUAKE = "Earthquake"
    EARTHQUAKE_FIRE = "Earthquake fire"
    FIRE = "Fire"
    FLOOD_BACKING_UP_OF_DRAINS = "Flood - Backing up of Drains"
    FLOOD_NON_COASTAL = "Flood - Non-Coastal"
    FREEZE_OR_ICE = "Freeze or Ice"
    GROUND_WATER_FLOOD = "Ground Water flood"
    HAIL = "Hail"
    HURRICANE = "Hurricane"
    LANDSLIDE = "Landslide"
    LIGHTNING = "Lightning"
    MUDSLIDE = "Mudslide"
    RAIN = "Rain"
    RESERVOIR_FLOOD = "Reservoir flood"
    RIOTS = "Riots"
    RIVER_FLOOD = "River flood"
    RUN_OFF_FLOOD = "Run-off flood"
    SMOKE = "Smoke"
    SNOW = "Snow"
    SPRINLER_LEAKAGE = "Sprinler leakage"
    STRIKES = "Strikes"
    STROM = "Strom"
    SUBSIDENCE = "Subsidence"
    TEMPEST = "Tempest"
    TERRORISM = "Terrorism"
    TSUNAMI = "Tsunami"
    TYPHOON = "Typhoon"
    WAR = "War"
    WEIGHT_OF_SNOW = "Weight of Snow"
    WIND_STORM = "Wind Storm"
    def __init__(self):  # noqa: E501
        """PropertyPeril - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'PropertyPeril':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The propertyPeril of this PropertyPeril.  # noqa: E501
        :rtype: PropertyPeril
        """
        return util.deserialize_model(dikt, cls)
