# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReceiptType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NEW_POLICY = "new policy"
    POLICY_RENEWAL = "policy renewal"
    MID_TERM_ADJUSTMENT = "mid term adjustment"
    CLAIM_PAYMENT = "claim payment"
    BROKERAGE_PAYMENT = "brokerage payment"
    PROFIT_SHARE_PAYMENT = "profit share payment"
    OTHER = "other"
    def __init__(self):  # noqa: E501
        """ReceiptType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ReceiptType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The receiptType of this ReceiptType.  # noqa: E501
        :rtype: ReceiptType
        """
        return util.deserialize_model(dikt, cls)
