# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RootConstruction(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ALUMINIUM = "Aluminium"
    ASBESTOS = "Asbestos"
    ASPHALT = "Asphalt"
    CONCRETE = "Concrete"
    COPPER = "Copper"
    CORRUGATED_IRON = "Corrugated Iron"
    ETHYLENE_PROPYLENE_DIENE_MONOMER_EPDM = "Ethylene Propylene Diene Monomer EPDM"
    FELT_ON_TIMBER = "Felt On Timber"
    FIBREGLASS = "Fibreglass"
    GLASS = "Glass"
    GREEN_ROOFS = "Green Roofs"
    LEAD = "Lead"
    METAL = "Metal"
    OTHER = "Other"
    PLASTIC = "Plastic"
    POLYCARBONATE = "Polycarbonate"
    REINFORCED_PVC = "Reinforced PVC"
    SHINGLE = "Shingle"
    SHINGLE_ASPHALT = "Shingle - Asphalt"
    SHINGLE_PINE_SPRUCE_CEDAR = "Shingle - Pine/Spruce/Cedar"
    SLATE = "Slate"
    STANDARD_CONSTRUCTION = "Standard Construction"
    STRAMIT = "Stramit"
    THATCH_FIBRE = "Thatch - Fibre"
    THATCH_REED = "Thatch - Reed"
    TILE = "Tile"
    TIMBER = "Timber"
    TURNERISED = "Turnerised"
    WOODWORK_CONSTRUCTION = "Woodwork Construction"
    ZINC = "Zinc"
    def __init__(self):  # noqa: E501
        """RootConstruction - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'RootConstruction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The rootConstruction of this RootConstruction.  # noqa: E501
        :rtype: RootConstruction
        """
        return util.deserialize_model(dikt, cls)
