# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TermLifeRiders(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ACCIDENTAL_DEATH_BENEFIT = "Accidental death benefit"
    TOTAL_PERMANENT_DISABILITY = "Total permanent disability"
    TOTAL_AND_PARTIAL_PERMANENT_DISABILITY = "Total and partial permanent disability"
    CRITICAL_ILLNESS = "Critical illness"
    CONVERTIBLE_TERM = "Convertible term"
    def __init__(self):  # noqa: E501
        """TermLifeRiders - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TermLifeRiders':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The termLifeRiders of this TermLifeRiders.  # noqa: E501
        :rtype: TermLifeRiders
        """
        return util.deserialize_model(dikt, cls)
