# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WallConstruction(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ALUMINIUM = "Aluminium"
    ASBESTOS = "Asbestos"
    BRICK = "Brick"
    BUNGAROOSH = "Bungaroosh"
    CLAY_LUMP_ADOBE = "Clay-Lump/Adobe"
    CLUNCH = "Clunch"
    COB_CONSTRUCTION = "Cob Construction"
    CONCRETE = "Concrete"
    CORRUGATED_IRON = "Corrugated Iron"
    ESSEX_CONSTRUCTION = "Essex Construction"
    FIBREGLASS_CONSTRUCTION = "Fibreglass Construction"
    FLINT = "Flint"
    GLASS = "Glass"
    LATHE_AND_PLASTER = "Lathe And Plaster"
    METAL = "Metal"
    MUNDIC_BLOCK = "Mundic Block"
    OTHER = "Other"
    PLASTIC = "Plastic"
    PREFABRICATED_BUILDING_COMBUSTIBLE_MATERIALS = "Prefabricated Building - Combustible Materials"
    PREFABRICATED_BUILDING_NON_COMBUSTIBLE_MATERIALS = "Prefabricated Building - Non Combustible Materials"
    STANDARD_CONSTRUCTION = "Standard Construction"
    STEEL_FRAME = "Steel Frame"
    STEEL_FRAME_BRICK = "Steel Frame/Brick"
    STEEL_FRAME_RENDER_OR_PEBBLEDASH = "Steel Frame/Render Or Pebbledash"
    STEEL_FRAME_TILE = "Steel Frame/Tile"
    STEEL_FRAME_WOOD_SHIPLAP = "Steel Frame/Wood Shiplap"
    STONE = "Stone"
    STRAMIT_CONSTRUCTION = "Stramit Construction"
    STRAW_BALE = "Straw Bale"
    STRUCTURALLY_INSULATED_PANELS_SIPS_ = "Structurally Insulated Panels (SIPs)"
    TIMBER = "Timber"
    TIMBER_FRAME = "Timber Frame"
    TIMBER_FRAME_BRICK = "Timber Frame/Brick"
    TIMBER_FRAME_LATHE_AND_PLASTER = "Timber Frame/Lathe And Plaster"
    TIMBER_FRAME_STONE = "Timber Frame/Stone"
    TIMBER_FRAME_TIMBER = "Timber Frame/Timber"
    TIMBER_PLASTER = "Timber/Plaster"
    WATTLE_AND_DAUB_CONSTRUCTION = "Wattle And Daub Construction"
    WOODWALL = "Woodwall"
    WOODWORK_CONSTRUCTION = "Woodwork Construction"
    def __init__(self):  # noqa: E501
        """WallConstruction - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'WallConstruction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The wallConstruction of this WallConstruction.  # noqa: E501
        :rtype: WallConstruction
        """
        return util.deserialize_model(dikt, cls)
